### PR TITLE
Tripetto integration

### PR DESCRIPTION
**Pull request by afixoftrix**
I have integrated Tripetto into the app. What left is styling and functionality.
 
For styling, I will work on making the app responsive and afterwards turn the app into a PWA.
For functionality, we will need an API to receive form submissions.

I have also created a `.env` file to contain api keys and other such documents. Backend needs to be notified about this.

Visual Update of PR:
Screen Shot 2020-05-18 at 8 13 19 PM

### CODE REVIEW

**Comment by afixoftrix** [comment]
@Murkantilism Since it's a private repo I guess it's okay. Will add.

**Comment by BrennenHodge** [comment]
Thanks for taking the lead here, @afixoftrix. Don't worry about fitting the survey on the dashboard. Let's just put a check-in option on the dashboard that will open covidx.app/health-report.

Here's what our dashboard should roughly look like: 

Dashboard with Check in

Also, check with @jaredigms and #19 regarding PWA functionality. 

@Murkantilism @afixoftrix Are you referring to the COVIDx repo being private?

**Comment by Murkantilism** [comment]
> @Murkantilism @afixoftrix Are you referring to the COVIDx repo being private?

@BrennenHodge Yes, it is right? I seem to recall I couldn't access it until given permission. If it isn't we should make it private or pull the `.env` file back out of source control.

**Comment by BrennenHodge** [comment]
@Murkantilism The repo is **not** private and the whole project is open source under an MIT license.

**Comment by BrennenHodge** [comment]
Well... These are our settings:

screenshot-github com-2020 05 19-10_49_20

Let's keep the project public as that's how it was launched. I'll lean on your decision for the .env file.

**Pull request merged**
