### PR TITLE
Large modal

### PR DESCRIPTION
**Pull request by afixoftrix**
This PR should center the tripetto form in an "xl" modal.

Screen Shot 2020-06-01 at 9 38 15 PM

### CODE REVIEW

**Comment by afixoftrix** [comment]
I'm not sure if this is what you were talking about @BrennenHodge.

**Comment by Murkantilism** [comment]
> I'm not sure if this is what you were talking about @BrennenHodge.

Seems like you pretty much nailed what he was looking for, to me

**Comment by BrennenHodge** [comment]
Looks good to me!

**Comment by Murkantilism** [comment]
@BrennenHodge deployed the latest to Production, XL form now live

**Pull request merged**
